### ISSUE TITLE
Test Done but i have no idea how to pull

### ISSUE THREAD

**Issue by MuhammadOwaisRahemo** [LaravelDaily/Test-Laravel-Eloquent-Basics#33]
Its helps more to me to be a perfect developer

**Comment by MuhammadOwaisRahemo** [comment]
> i have done the test and doesn't know how to pull request. please help

**Comment by imamhsn195** [comment]
If you don't know how to make a Pull Request, [here's my video with instructions](https://www.youtube.com/watch?v=vEcT6JIFji0).
